#ifndef QTHTMLPARSER_GLOBAL_H
#define QTHTMLPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTHTMLPARSER_LIBRARY)
#  define QTHTMLPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTHTMLPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTHTMLPARSER_GLOBAL_H
